version: '3'
services:
  mysql:
    image: mysql:8
    restart: always
    cap_add:
      - SYS_NICE
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - "${DATA_DIR}/${PROJECT_NAME}_${RAILS_ENV}/mysql/data:/var/lib/mysql"
    networks:
      - net

  redis:
    image: "redis:alpine"
    restart: always
    networks:
      - net

  clickhouse:
    image: yandex/clickhouse-server:20.3
    restart: always
    volumes:
      - "${DATA_DIR}/${PROJECT_NAME}_${RAILS_ENV}/clickhouse/data:/var/lib/clickhouse"
      - "${DATA_DIR}/${PROJECT_NAME}_${RAILS_ENV}/clickhouse/logs:/var/log/clickhouse-server"
      - "./config/docker/${RAILS_ENV}/clickhouse/config:/etc/clickhouse-server"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - net

  web:
    env_file: ./.env
    depends_on:
      - mysql
    environment:
      RAILS_ENV: ${RAILS_ENV}
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    volumes:
      - "${DATA_DIR}/${PROJECT_NAME}_${RAILS_ENV}/rails/tmp:/app/tmp"
      - "${DATA_DIR}/${PROJECT_NAME}_${RAILS_ENV}/rails/log:/app/log"
      - "${DATA_DIR}/${PROJECT_NAME}_${RAILS_ENV}/rails/storage:/app/storage"
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - RAILS_ENV=${RAILS_ENV} # pass RAILS_ENV to docker build process https://stackoverflow.com/questions/52429984/docker-compose-build-environment-variable
    ports:
      - 3000:3000
    networks:
      - net

networks:
  net:

